### ISSUE TITLE
Fix iPython audio and image output

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad-ext-ipython#3]
Was previously Abjad issue 676:

Jeff is having trouble with audio and LilyPond output in iPython notebooks.

Audio:

* Timidity may compile without the `-Ov` (Ogg) output option

LilyPond:

* Nothing happens at all.

**Comment by jefftrevino** [comment]
To add some more specifics about image output, Imagemagick is currently failing with failure code -6 on render.

**Comment by jefftrevino** [comment]
All of these issues have been resolved. They were caused by homebrew install issues. Inline audio playback and cropped png render both work fine for me now.
