### ISSUE TITLE
iPython abjad.show() makes pdf locally instead of in ~/.abjad

### ISSUE THREAD

**Issue by MarkPerlman** [Abjad/abjad-ext-ipython#6]
In a Jupyter Notebook, using vanilla abjad, calling `abjad.show()` creates a pdf in my ~/.abjad folder and opens in a pdf viewer; all good.

When using the iPython extension (i.e. `%load_ext abjadext.ipython`), calling `abjad.show()` instead creates a pdf locally, in the same folder as my .ipynb, but this raises an error "Rendering failed" because the pdf is expected to be found in ~/.abjad.

`abjad.graph()` and `abjad.play()` iPython integration both work correctly.

**Comment by josiah-wolf-oberholtzer** [comment]
This should be fixed via #8
