### ISSUE TITLE
Is this project still active/being developed?

### ISSUE THREAD

**Issue by jgarte** [Abjad/abjad-ext-ipython#9]
Hi Trevor,

Is this project still active/being developed? 

I saw in the [changelog](https://github.com/Abjad/abjad/releases/tag/v3.4) for abjad 3.4 that ipython support was dropped.

**Comment by trevorbaca** [comment]
Hi Jorge,

I dropped support for it in Abjad 3.4!

Trevor.

**Comment by jgarte** [comment]
> Hi Jorge,
> 
> I dropped support for it in Abjad 3.4!
> 
> Trevor.

Ok, thanks for doubly confirming that

all best
